Sensitivity Analysis of D3tot agaist tau
```{r}
source("ams_initialize_script.R")
source("ivsc_4cmtct_shedct.R")

lseq = function(from, to, length.out){
    sequence = seq(log(from), log(to), length.out=length.out)
    sequence = exp(sequence)
    return(sequence)
}

# Specify the range of tau
tau0 = 5.8
tau.range = tau0*lseq(1,10,6)

# Global Variable
d <- read.csv("ivsc_4cmtct_shedct_param.csv")
param.as.double <- d$Value
names(param.as.double) <- d$Parameter
compartment = 2
tmax = 3*28
dose.nmol = 80*scale.mg2nmol
# model file
model <- ivsc_4cmtct_shedct()
init <- model$init(param.as.double)
```
Sensitvity analysis of Dtot3 against tau
```{r}
# Define a function with tau as the input and D3tot as the return
Dtot3 = function(tau){
  ev = eventTable(amount.units="nmol", time.units="days")
  sample.points = c(seq(-7, tmax, 0.1), 10^(-3:0)) # sample time, increment by 0.1
  sample.points = sort(sample.points)
  sample.points = unique(sample.points)
  ev$add.sampling(sample.points)
  ev$add.dosing(dose=dose.nmol, nbr.doses=floor(tmax/tau)+1, dosing.interval=tau,
                dosing.to=compartment)
      
  init = model$init(param.as.double)
  out = model$rxode$solve(param.as.double, ev, init)
  out = model$rxout(out)
  out = out[,c("time","Dtot3")]
  out = out %>% 
    mutate(tau = tau)
  return(out)
}

# sensitivity analysis
df = data.frame()
for (tau in tau.range){
  sim = Dtot3(tau=tau)
  df = rbind(df, sim)
}

# make tau a factor, so that on ggplot different tau has different color
df$tau <- factor(df$tau)


# plot the sensitivity analysis
g = ggplot(df, aes(x=time, y=Dtot3, color=tau)) +
  geom_point()
```

Sensitivity analysis of Ttot3 against tau 
```{r}
Ttot3 = function(tau){
  ev = eventTable(amount.units="nmol", time.units="days")
  sample.points = c(seq(-7, tmax, 0.1), 10^(-3:0)) # sample time, increment by 0.1
  sample.points = sort(sample.points)
  sample.points = unique(sample.points)
  ev$add.sampling(sample.points)
  ev$add.dosing(dose=dose.nmol, nbr.doses=floor(tmax/tau)+1, dosing.interval=tau,
                dosing.to=compartment)
      
  init = model$init(param.as.double)
  out = model$rxode$solve(param.as.double, ev, init)
  out = model$rxout(out)
  out = out[,c("time","Mtot3")]
  out = out %>% 
    mutate(tau = tau)
  return(out)
  
}

df = data.frame()
for (tau in tau.range){
  sim = Ttot3(tau=tau)
  df = rbind(df, sim)
}

# make tau a factor, so that on ggplot different tau has different color
df$tau <- factor(df$tau)


# plot the sensitivity analysis
g = ggplot(df, aes(x=time, y= Mtot3, color=tau)) +
  geom_point()
g

```
The conclusion from above is that tau dose not have an effect on Ttot3

# Basic sensitivity analysis of Dtot3 against kon3
```{r}
tau = 14
d = read.csv("ivsc_4cmtct_shedct_param.csv")
p = d$Value
names(p) = d$Parameter
param.as.double = p


# kon3 range
kon3.initial = param.as.double["kon3"]
kon3.range = kon3.initial*lseq(1,100,6)


Dtot3 = function(kon3){
  ev = eventTable(amount.units="nmol", time.units = "days")
  sample.points = c(seq(-7, tmax, 0.1), 10^(-3:0)) # sample time, increment by 0.1
  sample.points = sort(sample.points)
  sample.points = unique(sample.points)
  ev$add.sampling(sample.points)
  ev$add.dosing(dose=dose.nmol, nbr.doses=floor(tmax/tau)+1, dosing.interval=tau,
                dosing.to=compartment)
      
  param.as.double["kon3"]=kon3
  init = model$init(param.as.double)
  out = model$rxode$solve(param.as.double, ev, init)
  out = model$rxout(out)
  out = out[,c("time","Dtot3")]
  out = out %>% 
    mutate(kon3 = kon3)
  return(out)
}

# sensitivity analysis
df = data.frame()
for (kon3 in kon3.range){
  sim = Dtot3(kon3=kon3)
  df = rbind(df, sim)
}

# plot
g = ggplot(df, aes(x=time, y= Dtot3, color=kon3)) + geom_point()
g
```
# General basic sensitivity analysis of f against x
```{r}
# variable
d = read.csv("ivsc_4cmtct_shedct_param.csv")
p = d$Value
names(p) = d$Parameter
param.as.double = p

x = "kon3"
x.range = param.as.double[x]*lseq(1, 100, 6)
target = "Dtot3"


f = function(v){
  ev = eventTable(amount.units="nmol", time.units = "days")
  sample.points = c(seq(-7, tmax, 0.1), 10^(-3:0)) # sample time, increment by 0.1
  sample.points = sort(sample.points)
  sample.points = unique(sample.points)
  ev$add.sampling(sample.points)
  ev$add.dosing(dose=dose.nmol, nbr.doses=floor(tmax/tau)+1, dosing.interval=tau,
                dosing.to=compartment)
  
  param.as.double[x]=v
  init = model$init(param.as.double)
  out = model$rxode$solve(param.as.double, ev, init)
  out = model$rxout(out)
  out = out[,c("time",target)]
  out = out %>% 
    mutate(variable = v)
  return(out)
  
}

# sensitivity analysis
df = data.frame()
for (value in x.range){
  sim = f(v=value)
  df = rbind(df, sim)
}

g = ggplot(df, aes(time, y=get(target), color=variable)) + geom_point()
g
```