---
title: "Task05e_Sensitivity_Analysis_pt2"
author: "Miandra Ellis"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
   html_document:
     toc: true
     toc_float: true
     code_folding: hide
---

# Preliminary stuff

```{r, warning=FALSE}
# Need this to get rxode working. I don't know why I keep having to run this.
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/RBuildTools/3.4/bin/",
            "C:/RBuildTools/3.4/mingw_64/bin", sep = ";"))
Sys.setenv(BINPREF = "C:/RBuildTools/3.4/mingw_64/bin/")

# To be called at the top of every Rmd file. Initialization code and some useful constants.
suppressMessages(source("ams_initialize_script.R"))
```

# Create data frame for multiple drugs and parameters.

```{r, include=FALSE}

# Note: Insoluble and soluble drugs are treated differently. 
# For insoluble, Tacc = M3totss/M30. For soluble, Tacc = S3totss/S30. 
# We are also interested in different parameters in the SA for either case.
# See writeup for details.

# --------------------------------------------------------------------------------
# Initialize.
# --------------------------------------------------------------------------------

# Load model.
model = ivsc_4cmtct_shedct(target = TRUE)
# Drugs to explore. 
drugs = c("Atezolizumab", "Trastuzumab", "Pembrolizumab", "Bevacizumab")
# List of parameters of interest.
parameters = c("dose", "ksynM3", "k13D","k13DM", "kshedDM3")
# names(parameters) = parameters
# Create vector of soluble drugs.
soluble = "Bevacizumab"

# Create paths to data files for each drug.
paths = NULL
for (i in 1:length(drugs)) {
  paths[i] = paste0("../data/ModelF_", drugs[i],"_Params.xlsx")
}

# Dose time, frequency, compartment, nominal dose
tmax = 26*7 #days
tau  = 21   #days
compartment = 2
dose.nmol = 10*scale.mpk2nmol
joined = NULL
isSoluble = FALSE

# --------------------------------------------------------------------------------
# Iterate over all the drugs.
# --------------------------------------------------------------------------------

for (i in 1:length(drugs)){
  # Load parameters.
  param.as.double =  read.param.file(paths[i])
  df_param =  as.data.frame(t(param.as.double))
  
  # Check if drug has soluble target.
  if (drugs[i] %in% soluble) {
    # Change any non-shed parameters including M to S.
    parameters = sapply(parameters, 
                        function(x) {
                          if (!grepl("shed|dose",x)) {return(gsub("M","S", x))}
                          return(x)
                        })
    isSoluble = TRUE
  }

  # Set range for parameters of interest in SA.
  # Check which parameters are nonzero, not including dose which isn't in df_param.
  nnzero = df_param[parameters[which(parameters != "dose")]] != 0
  nnzero = colnames(nnzero)[which(nnzero)]
  params.to.iterate = data.frame(lapply(df_param[nnzero], function(x) lseq(x*0.01, x*10, 13)))
  
  dfs = list()
  # Iterate all of the parameters for a single drug.
  for (j in 1:ncol(params.to.iterate)){
    dfs[[j]] = compare.thy.sim(model = model,
                               param.as.double = param.as.double,
                               dose.nmol = dose.nmol,
                               tmax = tmax,
                               tau  = tau,
                               compartment = compartment,
                               param.to.change = names(params.to.iterate)[j],
                               param.to.change.range = params.to.iterate[[j]],
                               soluble = isSoluble)
    dfs[[j]] = dfs[[j]] %>% mutate(drug = drugs[i], isSol = isSoluble)
  }
  joined = bind_rows(joined,dfs)
  
  # Reset isSoluble to false since the default in compare.thy.sim is false.
  isSoluble = FALSE
}

joined = joined %>%
  mutate(drug = factor(drug,levels=c("Bevacizumab","Pembrolizumab","Atezolizumab", "Trastuzumab")))
```

# Plot the output variable of interest

```{r}

# I only wanted a subset of the parameters for gather.
joined.g = joined %>%
  select(-AFIRT,-TFIRT) %>%
  mutate(T30                = ifelse(isSol,S30,M30),
         Cavg3_Thresh       = Cavg3 < 10*T30,
         Thiele_Thresh      = Thiele > 0.2,
         Assumptions.Failed = ifelse(Cavg3_Thresh | Thiele_Thresh,0.2, NA)) %>%
  select(                 fold.change.param,param,param,drug,isSol,starts_with("AFIRT"),starts_with("TFIRT"),"Assumptions.Failed") %>%
  gather(Measure,Value,-c(fold.change.param,param,param,drug,isSol)) %>%
  filter(!is.na(Value))

#Rename for plotting - map M->T and S->T (for target)
joined.g.plot = joined.g %>%
  mutate(param  = str_replace(param,"M","T"),
         param  = str_replace(param,"S","T"),
         key    = case_when(Measure=="Assumptions.Failed" ~ "Assumptions.Failed",
                            str_detect(Measure,"sim$") ~ "Simulation",
                            TRUE                       ~ "Theory"),
         Target = ifelse(isSol,"Soluble","Membrane-Bd"),
         Target = factor(Target,levels=c("Soluble","Membrane-Bd")))

data = filter(joined.g.plot,Measure %in% c("AFIRT.Kssd","AFIRT.sim","Assumptions.Failed"))
g = ggplot(data, aes(fold.change.param, Value, color=key,linetype=key,size=key,alpha=key))
g = g + scale.x.log10(limits=c(.009,11))
g = g + scale.y.log10(limits=c(.001,1))
g = g + geom_line()
g = g + facet_grid(drug + Target ~ param, switch = "y")
g = g + labs(x="Fold Change in Parameter",
             y="AFTIR",
             color    = "",
             linetype = "",
             size     = "",
             alpha    = "")
g = g + theme(legend.position="bottom", 
              text=element_text(size=15), 
              axis.title.x=element_text(size=20), 
              axis.title.y=element_text(size=20))
g = g + scale_linetype_manual(values  = c(Simulation   = "solid",
                                          Theory       = "longdash",
                                          Assumptions.Failed = "solid"))
g = g + scale_color_manual(values     = c(Simulation   = "black",
                                          Theory       = "blue",
                                          Assumptions.Failed = "red"))
g = g + scale_size_manual(values      = c(Simulation   = 1,
                                          Theory       = 1,
                                          Assumptions.Failed = 3))
g = g + scale_alpha_manual(values     = c(Simulation   = 1,
                                          Theory       = 1,
                                          Assumptions.Failed = .5))
width  = 10
height = 7
print(g)
ggsave("../results/Task05e_AFTIR.Kssd.pdf",width = width,height=height)
```

#Loop through the other plots
```{r}
plot.string.list = c("AFIRT.Kss","AFIRT.Kd","TFIRT.Kssd","TFIRT.Kss","TFIRT.Kd")
for (plot.string in plot.string.list) {
  save.string = str_replace(plot.string,"\\.","_")
  data = filter(joined.g.plot,Measure %in% c(plot.string,
                                             paste0(paste0(substr(plot.string,1,5)),".sim"),
                                             "Assumptions.Failed"))
  g = g %+% data
  g = g + ylab(ifelse(substr(plot.string,1,1)=="A","AFTIR","TFTIR"))
  plot(g)
  ggsave(paste0("../results/Task05e_",save.string,".pdf"),width = width,height=height)
}
```
