---
title: "Task04_Sensitivity_Analysis"
author: "Sameed Ahmed"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
# output:
#   html_document:
#     toc: true
#     toc_float: true
#     code_folding: hide
---

# Preliminary stuff

```{r, warning=FALSE}
# Need this to get rxode working. I don't know why I keep having to run this.
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/RBuildTools/3.4/bin/",
            "C:/RBuildTools/3.4/mingw_64/bin", sep = ";"))
Sys.setenv(BINPREF = "C:/RBuildTools/3.4/mingw_64/bin/")

# To be called at the top of every Rmd file. Initialization code and some useful constants.
suppressMessages(source("ams_initialize_script.R"))
```

# Function to compute sensitivity analysis

```{r}

# This function does the sensitivity analysis on the user inputted parameter and compares the theoretical result to the simulated result.

# Input: 
# model - model system of ODE's solved with RxODE. In this project, it is 'ivsc_4cmtct_shedct'.
# param.as.double - read parameters from Excel file. read.param.file("file directory").
# dose.nmol - dose in nmol.
# tmax - time of treatment in days
# tau - frequency of administering dose in days
# compartment - compartment where drug is administered
# param.to.change - parameter on which to do SA. This must be a string.
# param.to.change.range - range of parameter on which to do SA. The range must be symmetric in fold change. This must be a vector of odd length.

# Output:
# Plot of theoretical and simulated AFIRT vs fold change in parameter
# Data frame of AFIRT vs parameter value

compare.thy.sim = function(model = model, 
                           param.as.double = param.as.double,
                           dose.nmol = dose.nmol,
                           tmax = tmax,
                           tau = tau,
                           compartment = compartment,
                           param.to.change = param.to.change,
                           param.to.change.range = param.to.change.range) {
  
  # Evaluate model ------------------------------------------------------------------------------------------

  # Put all simulations for different dose into one data frame.
  df_sim = data.frame()
  
  # Iterate through values in simulation.
  if (param.to.change == 'dose'){
    for (param.iter in param.to.change.range){
      row = lumped.parameters.simulation(model, param.as.double, param.iter, tmax, tau, compartment)
      df_sim = rbind(df_sim, row)
    }  
  } else {
    for (param.iter in param.to.change.range){
    param.as.double[param.to.change] = param.iter
    row = lumped.parameters.simulation(model, param.as.double, dose.nmol, tmax, tau, compartment)
    df_sim = rbind(df_sim, row)
    }
  }
  df_sim$param.to.change = param.to.change.range
  
  # Put all theoretical calculations for different dose into one data frame.
  df_thy = data.frame()
  
  # Iterate through values in theory.
  if (param.to.change == 'dose'){
    for (param.iter in param.to.change.range){
      row = lumped.parameters.theory(param.as.double, param.iter, tau)
      df_thy = rbind(df_thy, row)
    }
  } else{
    for (param.iter in param.to.change.range){
      param.as.double[param.to.change] = param.iter
      row = lumped.parameters.theory(param.as.double, dose.nmol, tau)
      df_thy = rbind(df_thy, row)
    }
  }
  df_thy = df_thy %>% mutate(param.to.change = param.to.change.range)
  
  # Arrange theory and simulation into single data frame.
  df_compare = bind_rows(df_thy,df_sim)
  df_compare = df_compare %>%
    arrange(param.to.change,type) %>%
    mutate_if(is.numeric,signif,2)
  
  # Plot results --------------------------------------------------------------------------------------------
  
  # Arrange data in a way suitable for plotting.
  Param  = data.frame(Param = param.to.change.range/median(param.to.change.range))
  AFIRT  = data.frame(AFIRT.sim  = df_sim$AFIRT.sim,
                      AFIRT.Kssd = df_thy$AFIRT.Kssd,
                      AFIRT.Kss  = df_thy$AFIRT.Kss,
                      AFIRT.Kd   = df_thy$AFIRT.Kd)
  Data  = data.frame(Param, AFIRT)
  names = names(Data)
  Data  = Data %>% gather(key, AFIRT.value, -c(get(names[1])))

  # Plot all AFIRT's on same axes.
  g = ggplot(Data, aes(Param, AFIRT.value, color=key)) +
      # ylim(10^(-4), 1) + 
      scale.x.log10() +
      scale.y.log10(limits=c(10^(-3), 10^(1))) + 
      geom_line() +
      geom_point() + 
      labs(x = param.to.change)
  print(g)
  
  return(df_compare)
}
```

# Example of calling this function

```{r}
# Load model and parameters.
model           = ivsc_4cmtct_shedct()
param.as.double = read.param.file("../data/ModelF_Atezolizumab_Params.xlsx")
df_param        = as.data.frame(t(param.as.double))
dose.nmol       = scale.mpk2nmol

# Set range for parameters of interest in SA.
dose.nmol.range = lseq(.1,10,7)*scale.mpk2nmol
ksynM3.range    = lseq(df_param$ksynM3  *.1, df_param$ksynM3  *10, 7)
kshedM3.range   = lseq(df_param$kshedM3 *.1, df_param$kshedM3 *10, 7)
kshedDM3.range  = lseq(df_param$kshedDM3*.1, df_param$kshedDM3*10, 7)
k13D.range      = lseq(df_param$k13D    *.1, df_param$k13D    *10, 7)
# k13DM.range     = lseq(df_param$k13DM   *.1, df_param$k13DM   *10, 7)
# k31DM.range     = lseq(df_param$k31DM   *.1, df_param$k31DM   *10, 7)
VD3.range       = lseq(df_param$VD3     *.1, df_param$VD3     *10, 7)

# Dose time, frequency, and compartment
tmax = 26*7 #days
tau  = 21   #days
compartment = 2

df_compare = compare.thy.sim(model = model,
                             param.as.double = param.as.double,
                             dose.nmol = dose.nmol,
                             tmax = tmax,
                             tau  = tau,
                             compartment = compartment,
                             param.to.change = 'kshedDM3',
                             param.to.change.range = kshedDM3.range)
```































